### ISSUE TITLE
RClone logs Mbytes/Kbytes/Bytes

### ISSUE THREAD

**Issue by antigravity83** [cgomesu/mediscripts-shared#4]
Hi

My rclone logs show Mbytes/Kbytes/Bytes instead of MiB/s, KiB's etc. 

I changed your script to look for Mbytes instead, however got an error:

`./googleapis.sh: line 231: [: : integer expression expected`

Any ideas on how to get the script to work? Happy to change rclone output to MiB's/KiB's if necessary. Just not sure how!

**Comment by cgomesu** [comment]
> My rclone logs show Mbytes/Kbytes/Bytes instead of MiB/s, KiB's etc.

please provide a copy of the rclone log file that contain such metrics

> I changed your script to look for Mbytes instead

what did you change exactly?  I assume you're referring to the bit at https://github.com/cgomesu/mediscripts-shared/blob/main/googleapis.sh#L226-L245 but confirm.

**Comment by cgomesu** [comment]
> `./googleapis.sh: line 231: [: : integer expression expected`

this issue in particular is telling you that the variable `$SPEED_INT` is not an integer and it was expecting one for the test on L231, which means that `SPEED_INT="$(echo "$SPEED" | cut -f 1 -d '.')"` is not parsing the value from `$SPEED` correctly.  this probably happens because your log files looks different than the ones I've tested before, which is why I need to see how it looks to propose a fix.

**Comment by antigravity83** [comment]
Edit// Nevermind - script works now! When I was changing MiB's to MBytes I incorrectly listed Mbytes. 

Will leave the below if anyone else needs to make this change.

> please provide a copy of the rclone log file that contain such metrics

Thanks - here is what the rclone copy log looks like

```
2022/07/12 12:15:04 INFO  :
Transferred:           50M / 50 MBytes, 100%, 42.573 MBytes/s, ETA 0s
Transferred:            1 / 1, 100%
Elapsed time:         1.1s
```

> what did you change exactly?

I changed any reference to MiB's to MBytes, and KiB's to KBytes

```
# parse log file
  if [ -f "$RCLONE_LOG" ]; then
    if grep -qi "failed" "$RCLONE_LOG"; then
      msg "Unable to connect with $IP." 'WARNING'
    else
      msg "Parsing connection with $IP." 'INFO'
      # only whitelist MiB/s connections
      if grep -qi "MBytes" "$RCLONE_LOG"; then
        SPEED=$(grep "MBytes" "$RCLONE_LOG" | cut -d, -f3 | cut -c 2- | cut -c -5 | tail -1)
        # use speed criterion to decide whether to whilelist or not
        SPEED_INT="$(echo "$SPEED" | cut -f 1 -d '.')"
        if [ "$SPEED_INT" -gt "${SPEED_CRITERION:-$DEFAULT_SPEED_CRITERION}" ]; then
          # good endpoint
          msg "$SPEED MBytes. Above criterion endpoint. Whitelisting IP '$IP'." 'INFO'
          echo "$IP" | tee -a "$LOCAL_TMP_SPEEDRESULTS_DIR$SPEED" > /dev/null
        else
          # below criterion endpoint
          msg "$SPEED MBytes. Below criterion endpoint. Blacklisting IP '$IP'." 'INFO'
          echo "$IP" | tee -a "$BLACKLIST" > /dev/null
        fi
      elif grep -qi "KBytes" "$RCLONE_LOG"; then
        SPEED=$(grep "KBytes" "$RCLONE_LOG" | cut -d, -f3 | cut -c 2- | cut -c -5 | tail -1)
        msg "$SPEED KBytes. Abnormal endpoint. Blacklisting IP '$IP'." 'WARNING'
        echo "$IP" | tee -a "$BLACKLIST" > /dev/null
      else
        # assuming it's either KiB/s or MiB/s, else parses as error and do nothing
        msg "Could not parse connection with IP '$IP'." 'WARNING'
      fi
    fi
    # local cleanup of tmp file and log
    rm "$LOCAL_TMP_TESTFILE_DIR${REMOTE_TEST_FILE:-$DEFAULT_REMOTE_TEST_FILE}" > /dev/null 2>&1
    rm "$RCLONE_LOG" > /dev/null 2>&1
  fi
```

**Comment by cgomesu** [comment]
> Edit// Nevermind - script works now! When I was changing MiB's to MBytes I incorrectly listed Mbytes.
>
> Will leave the below if anyone else needs to make this change.

okay. in any case, I'll have a little bit of free time today and will see if I can edit the current script to make it compatible with such metrics. this should make it easier for anyone else running into the same issue as you.

**Comment by cgomesu** [comment]
@antigravity83, I wrote a fix for this issue (#6). Please test it and let me know if it fixes the issue.  If you're not sure how to clone that particular branch, just download the raw edited script, chmod it, edit the variables at the top to match your case, and then run it:

```
cd ~
wget https://raw.githubusercontent.com/cgomesu/mediscripts-shared/89d5f275e11dea571e8e55a69e151433e6930c23/googleapis.sh
chmod +x googleapis.sh
nano googleapis.sh
sudo ./googleapis.sh
```

**Comment by antigravity83** [comment]
> 

Sorry for taking so long to reply - recently had a baby so spare time is short!

Tested your updated file and it works perfectly. Appreciate the precheck too. Saves checking all the IP's each run.

**Comment by cgomesu** [comment]
no worries.  congrats on the baby!

> Tested your updated file and it works perfectly. Appreciate the precheck too. Saves checking all the IP's each run.

alright.  i'll go ahead and merge the changes into main then.
